<?php

namespace ProjectBundle\Model;

use Enhavo\Bundle\ContactBundle\Model\Contact as BaseContact;
use Enhavo\Bundle\ContactBundle\Model\ContactInterface;


class Contact extends BaseContact implements ContactInterface
{

    public function setEmail($email)
    {
        parent::setEmail($email); // TODO: Change the autogenerated stub
    }

    public function setFirstName($firstName)
    {
        parent::setFirstName($firstName); // TODO: Change the autogenerated stub
    }

    public function setMessage($message)
    {
        parent::setMessage($message); // TODO: Change the autogenerated stub
    }
}
