parameters:
  locale: en

enhavo_app:
    menu:
        dashboard:
            type: dashboard
        user:
            type: user_user
        group:
            type: user_group
        article:
            type: article
        page:
            type: page
        category:
            type: category
        download:
            type: download
        slider:
            type: slider
        newsletter:
            type: newsletter_newsletter
        subscriber:
            type: newsletter_subscriber
        calendar:
            type: calendar
        product:
            type: shop_product
        order:
            type: shop_order
        setting:
            type: setting
        translation-strings:
            type: translation
        project:
            type: base
            label: Project
            route: project_project_index
            role: ROLE_ENHAVO_PROJECT_PROJECT_INDEX
            icon: box


enhavo_grid:
    items:
        picture:
            type: picture
        picture_picture:
            type: picture_picture
        three_picture:
            type: three_picture
        gallery:
            type: gallery
        text:
            type: text
        text_picture:
            type: text_picture
        text_text:
            type: text_text
        cite_text:
            type: cite_text
        download:
            type: download
        video:
            type: video


sylius_resource:
    resources:
        project.project:
            classes:
                model: ProjectBundle\Entity\Project
                controller: Enhavo\Bundle\AppBundle\Controller\ResourceController
                form:
                    default: ProjectBundle\Form\Type\ProjectType