project_project_index:
    options:
        expose: true
    path: /project/project/index
    methods: [GET]
    defaults:
        _controller: project.controller.project:indexAction
        _sylius:
            viewer:

project_project_create:
    options:
        expose: true
    path: /project/project/create
    methods: [GET,POST]
    defaults:
        _controller: project.controller.project:createAction
        _sylius:
            viewer:

project_project_update:
    options:
        expose: true
    path: /project/project/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: project.controller.project:updateAction
        _sylius:
            viewer:

project_project_table:
    options:
        expose: true
    path: /project/project/table
    methods: [GET]
    defaults:
        _controller: project.controller.project:tableAction
        _sylius:
            viewer:

project_project_delete:
    options:
        expose: true
    path: /project/project/delete/{id}
    methods: [DELETE]
    defaults:
        _controller: project.controller.project:deleteAction

project_project_batch:
    options:
        expose: true
    path: /project/project/batch
    methods: [POST]
    defaults:
        _controller: project.controller.project:batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete
                    label: table.batch.action.delete
                    confirm_message: table.batch.message.confirm.delete
                    translation_domain: EnhavoAppBundle
                    permission: ROLE_ENHAVO_PAGE_PAGE_DELETE
                    position: 0
                publish:
                    type: publish
                    label: page.batch.action.publish
                    confirm_message: page.batch.message.confirm.publish
                    translation_domain: EnhavoPageBundle
                    permission: ROLE_ENHAVO_PAGE_PAGE_EDIT
                    position: 1

project_project_preview:
    options:
        expose: true
    path: /project/project/preview
    methods: [POST]
    defaults:
        _controller: project.controller.project:previewAction
        _sylius:
            viewer:

#IF PROBLEMS OCCOURE
# composer update enhavo/enhavo
