ProjectBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: ProjectBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
        firstName:
            type: string
            length: 255
        message:
            type: string
            length: 255
    lifecycleCallbacks: {  }
