services:
    project.form.project:
        class: ProjectBundle\Form\Type\ProjectType
        tags:
            - { name: form.type, alias: 'project_project' }
#    project.form.contact:
#        class: ProjectBundle\Form\Type\ContactType
#        tags:
#            - { name: form.type, alias: 'project_contact' }
